<?php

if (!defined('ABSPATH')) {
	exit;
}

add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_682100e909f77',
		'title' => 'Автор',
		'fields' => array(
			array(
				'key' => 'field_682100e9990a7',
				'label' => 'Аватар',
				'name' => 'hp_author_avatar',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'Загрузите аватар (фотографию) автора, если она у него есть.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'uploadedTo',
				'min_width' => 320,
				'min_height' => 320,
				'min_size' => '',
				'max_width' => 2048,
				'max_height' => 2048,
				'max_size' => 5,
				'mime_types' => '.png, .jpg, .jpeg, .webp',
				'preview_size' => 'large',
			),
			array(
				'key' => 'field_68210190990a8',
				'label' => 'Имя',
				'name' => 'hp_author_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите имя автора',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Имя',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_682101d9990a9',
				'label' => 'Фамилия',
				'name' => 'hp_author_secondname',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите фамилию автора',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Фамилия',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_68210207990aa',
				'label' => 'Отчество',
				'name' => 'hp_author_thirtname',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите отчество автора (если оно есть)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Отчество',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_68210250990ab',
				'label' => 'Биография',
				'name' => 'hp_author_bio',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => 'Опишите биографию автора, чтобы читатель мог ближе познакомиться с автором',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_682102cf990ac',
				'label' => 'Награды и рейтинги',
				'name' => 'hp_author_achievements',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => 'Вы можете указать награды и рейтинги автора',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'pagination' => 0,
				'min' => 0,
				'max' => 120,
				'collapsed' => '',
				'button_label' => 'Добавить',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_68210359990ad',
						'label' => 'Дата достижения',
						'name' => 'hr_author_date_achievement',
						'aria-label' => '',
						'type' => 'date_picker',
						'instructions' => 'Год получения достижения',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'Y',
						'return_format' => 'Y',
						'first_day' => 1,
						'parent_repeater' => 'field_682102cf990ac',
					),
					array(
						'key' => 'field_682103dd990ae',
						'label' => 'Описание достижения',
						'name' => 'hp_author_achievement_description',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => 'Опишите полученное достижение',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => 300,
						'placeholder' => 'Краткое описание достижения',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_682102cf990ac',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'hp_authors',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_682115a403be1',
		'title' => 'Книга',
		'fields' => array(
			array(
				'key' => 'field_682115a4f73be',
				'label' => 'Название',
				'name' => 'hp_book_title',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажаите название книги',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 255,
				'placeholder' => 'Низвание книги',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_682115faf73bf',
				'label' => 'Возрастное ограничение (флаг)',
				'name' => 'hp_book_age_check',
				'aria-label' => '',
				'type' => 'true_false',
				'instructions' => 'Укажите возрастное ограничение для книги, если оно есть',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => 'Есть ограничение?',
				'default_value' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
				'ui' => 1,
			),
			array(
				'key' => 'field_68211680f73c0',
				'label' => 'Возрастное ограничение',
				'name' => 'hp_book_age_number',
				'aria-label' => '',
				'type' => 'number',
				'instructions' => 'Если у книги есть ограничение по возрасту - укажите его.',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_682115faf73bf',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 0,
				'min' => 0,
				'max' => 99,
				'placeholder' => 0,
				'step' => 1,
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_682116e8f73c1',
				'label' => 'Автор',
				'name' => 'hp_book_author',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => 'Укажите автора книги',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'hp_author',
				),
				'post_status' => array(
					0 => 'publish',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'return_format' => 'id',
				'min' => 1,
				'max' => 10,
				'elements' => '',
				'bidirectional' => 0,
				'bidirectional_target' => array(
				),
			),
			array(
				'key' => 'field_68211788f73c2',
				'label' => 'IBSN',
				'name' => 'hp_book_ibsn',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите IBSN книги',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 255,
				'placeholder' => 'IBSN',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_682117cef73c3',
				'label' => 'Год публикации',
				'name' => 'hp_book_year',
				'aria-label' => '',
				'type' => 'date_picker',
				'instructions' => 'Укажите год публикации книги',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'display_format' => 'Y',
				'return_format' => 'Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_6821181af73c4',
				'label' => 'Описание',
				'name' => 'hp_book_description',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => 'Дайте описание книги/произведения для читателей',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_682118c6abf9c',
				'label' => 'Рейтинг OZON',
				'name' => 'hp_book_ozon',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите рейтинг книги/произведения на маркетплейсе Ozon',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '0/10',
				'maxlength' => 10,
				'placeholder' => '0/10',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_68211982abf9d',
				'label' => 'Рейтинг WB',
				'name' => 'hp_book_wb',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите рейтинг книги/произведения на маркетплейсе WB',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '0/10',
				'maxlength' => 10,
				'placeholder' => '0/10',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6821199fabf9e',
				'label' => 'Галерея',
				'name' => 'hp_book-gallery',
				'aria-label' => '',
				'type' => 'gallery',
				'instructions' => 'Добавьте изображения книги',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'uploadedTo',
				'min' => 1,
				'max' => 24,
				'min_width' => 320,
				'min_height' => 320,
				'min_size' => '',
				'max_width' => 2048,
				'max_height' => 2048,
				'max_size' => 5,
				'mime_types' => '.png, .jpg, .jpeg, .webp',
				'insert' => 'append',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'hp_books',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'group_6821115b16d7d',
		'title' => 'Эксперт',
		'fields' => array(
			array(
				'key' => 'field_6821115b1d8f1',
				'label' => 'Аватар',
				'name' => 'hp_expert_avatar',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => 'Загрузите аватар (фотографию) эксперта, если он у него есть.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'uploadedTo',
				'min_width' => 320,
				'min_height' => 320,
				'min_size' => '',
				'max_width' => 2048,
				'max_height' => 2048,
				'max_size' => 5,
				'mime_types' => '.png, .jpg, .jpeg, .webp',
				'preview_size' => 'large',
			),
			array(
				'key' => 'field_6821115b21267',
				'label' => 'Имя',
				'name' => 'hp_expert_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите имя эксперта',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Имя',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6821115b24d0d',
				'label' => 'Фамилия',
				'name' => 'hp_expert_secondname',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите фамилию эксперта',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Фамилия',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6821115b288c4',
				'label' => 'Отчество',
				'name' => 'hp_expert_thirtname',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите отчество эксперта (если оно есть)',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Отчество',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_68211184ef92a',
				'label' => 'Профессия',
				'name' => 'hp_expert_prof',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => 'Укажите профессию эксперта',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => 120,
				'placeholder' => 'Профессия',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6821115b2c6d7',
				'label' => 'Об эксперте',
				'name' => 'hp_expert_bio',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => 'Опишите биографию эксперта, чтобы читатель мог ближе познакомиться с профессионалом',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'hp_experts',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
});

add_action('init', function () {
	register_taxonomy('hp_book_taxonomy', array(
		0 => 'books',
	), array(
		'labels' => array(
			'name' => 'Жанры',
			'singular_name' => 'Жанр',
			'menu_name' => 'Жанр',
			'all_items' => 'Все Жанр',
			'edit_item' => 'Изменить Жанр',
			'view_item' => 'Посмотреть Жанр',
			'update_item' => 'Обновить Жанр',
			'add_new_item' => 'Добавить новое Жанр',
			'new_item_name' => 'Новое Жанр название',
			'parent_item' => 'Родитель Жанр',
			'parent_item_colon' => 'Родитель Жанр:',
			'search_items' => 'Поиск Жанр',
			'not_found' => 'Не найдено жанр',
			'no_terms' => 'Нет жанр',
			'filter_by_item' => 'Фильтр по жанр',
			'items_list_navigation' => 'Жанр навигация по списку',
			'items_list' => 'Жанр список',
			'back_to_items' => '← Перейти к жанр',
			'item_link' => 'Cсылка на Жанр',
			'item_link_description' => 'Ссылка на жанр',
		),
		'public' => true,
		'hierarchical' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'default_term' => array(
			'name' => 'Без жанра',
			'slug' => 'out_of_tax',
		),
	));
});

add_action('init', function () {
	register_post_type('hp_authors', array(
		'labels' => array(
			'name' => 'Авторы',
			'singular_name' => 'Автор',
			'menu_name' => 'Авторы',
			'all_items' => 'Все Авторы',
			'edit_item' => 'Изменить Автор',
			'view_item' => 'Посмотреть Автор',
			'view_items' => 'Посмотреть Авторы',
			'add_new_item' => 'Добавить новое Автор',
			'add_new' => 'Добавить новое Автор',
			'new_item' => 'Новый Автор',
			'parent_item_colon' => 'Родитель Автор:',
			'search_items' => 'Поиск Авторы',
			'not_found' => 'Не найдено авторы',
			'not_found_in_trash' => 'В корзине не найдено авторы',
			'archives' => 'Архивы Автор',
			'attributes' => 'Атрибуты Автор',
			'insert_into_item' => 'Вставить в автор',
			'uploaded_to_this_item' => 'Загружено в это автор',
			'filter_items_list' => 'Фильтровать список авторы',
			'filter_by_date' => 'Фильтр авторы по дате',
			'items_list_navigation' => 'Авторы навигация по списку',
			'items_list' => 'Авторы список',
			'item_published' => 'Автор опубликовано.',
			'item_published_privately' => 'Автор опубликована приватно.',
			'item_reverted_to_draft' => 'Автор преобразован в черновик.',
			'item_scheduled' => 'Автор запланировано.',
			'item_updated' => 'Автор обновлён.',
			'item_link' => 'Cсылка на Автор',
			'item_link_description' => 'Ссылка на автор.',
		),
		'description' => 'Тип записей авторов',
		'public' => true,
		'hierarchical' => true,
		'show_in_rest' => true,
		'rest_base' => '/authors/',
		'menu_icon' => 'dashicons-admin-users',
		'supports' => array(
			0 => 'custom-fields',
		),
		'taxonomies' => array(
			0 => 'hp_book_taxonomy',
		),
		'rewrite' => array(
			'feeds' => true,
		),
		'delete_with_user' => false,
	));

	register_post_type('hp_books', array(
		'labels' => array(
			'name' => 'Книги',
			'singular_name' => 'Книга',
			'menu_name' => 'Книги',
			'all_items' => 'Все Книги',
			'edit_item' => 'Изменить Книга',
			'view_item' => 'Посмотреть Книга',
			'view_items' => 'Посмотреть Книги',
			'add_new_item' => 'Добавить новое Книга',
			'add_new' => 'Добавить новое Книга',
			'new_item' => 'Новый Книга',
			'parent_item_colon' => 'Родитель Книга:',
			'search_items' => 'Поиск Книги',
			'not_found' => 'Не найдено книги',
			'not_found_in_trash' => 'В корзине не найдено книги',
			'archives' => 'Архивы Книга',
			'attributes' => 'Атрибуты Книга',
			'insert_into_item' => 'Вставить в книга',
			'uploaded_to_this_item' => 'Загружено в это книга',
			'filter_items_list' => 'Фильтровать список книги',
			'filter_by_date' => 'Фильтр книги по дате',
			'items_list_navigation' => 'Книги навигация по списку',
			'items_list' => 'Книги список',
			'item_published' => 'Книга опубликовано.',
			'item_published_privately' => 'Книга опубликована приватно.',
			'item_reverted_to_draft' => 'Книга преобразован в черновик.',
			'item_scheduled' => 'Книга запланировано.',
			'item_updated' => 'Книга обновлён.',
			'item_link' => 'Cсылка на Книга',
			'item_link_description' => 'Ссылка на книга.',
		),
		'description' => 'Тип записей книг',
		'public' => true,
		'hierarchical' => true,
		'show_in_rest' => true,
		'rest_base' => 'books/',
		'menu_icon' => 'dashicons-book',
		'supports' => array(
			0 => 'custom-fields',
		),
		'taxonomies' => array(
			0 => 'hp_book_taxonomy',
		),
		'rewrite' => array(
			'feeds' => true,
		),
		'delete_with_user' => false,
	));

	register_post_type('hp_experts', array(
		'labels' => array(
			'name' => 'Эксперты',
			'singular_name' => 'Эксперт',
			'menu_name' => 'Эксперты',
			'all_items' => 'Все Эксперты',
			'edit_item' => 'Изменить Эксперт',
			'view_item' => 'Посмотреть Эксперт',
			'view_items' => 'Посмотреть Эксперты',
			'add_new_item' => 'Добавить новое Эксперт',
			'add_new' => 'Добавить новое Эксперт',
			'new_item' => 'Новый Эксперт',
			'parent_item_colon' => 'Родитель Эксперт:',
			'search_items' => 'Поиск Эксперты',
			'not_found' => 'Не найдено эксперты',
			'not_found_in_trash' => 'В корзине не найдено эксперты',
			'archives' => 'Архивы Эксперт',
			'attributes' => 'Атрибуты Эксперт',
			'insert_into_item' => 'Вставить в эксперт',
			'uploaded_to_this_item' => 'Загружено в это эксперт',
			'filter_items_list' => 'Фильтровать список эксперты',
			'filter_by_date' => 'Фильтр эксперты по дате',
			'items_list_navigation' => 'Эксперты навигация по списку',
			'items_list' => 'Эксперты список',
			'item_published' => 'Эксперт опубликовано.',
			'item_published_privately' => 'Эксперт опубликована приватно.',
			'item_reverted_to_draft' => 'Эксперт преобразован в черновик.',
			'item_scheduled' => 'Эксперт запланировано.',
			'item_updated' => 'Эксперт обновлён.',
			'item_link' => 'Cсылка на Эксперт',
			'item_link_description' => 'Ссылка на эксперт.',
		),
		'description' => 'Тип записей экспертов',
		'public' => true,
		'hierarchical' => true,
		'show_in_rest' => true,
		'rest_base' => 'experts/',
		'menu_icon' => 'dashicons-businessman',
		'supports' => array(
			0 => 'custom-fields',
		),
		'taxonomies' => array(
			0 => 'category',
		),
		'rewrite' => array(
			'feeds' => true,
		),
		'delete_with_user' => false,
	));
});

